# Compile wheels
# Reference: https://nanobind.readthedocs.io/en/latest/packaging.html#step-6-build-wheels-in-the-cloud
name: Wheels

# Only on manual trigger
on:
  workflow_dispatch:

# Publish Release need write permissions
permissions:
  contents: write

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: dist-sdist
        path: dist/*.tar.gz

  build_wheels:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux_x86_64
            runner: ubuntu-latest
            env_arch_key: CIBW_ARCHS_LINUX
            arch: x86_64
          - name: linux_aarch64
            runner: ubuntu-latest
            env_arch_key: CIBW_ARCHS_LINUX
            arch: aarch64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build wheels via cibuildwheel
      uses: pypa/cibuildwheel@v2.22
      env:
        ${{ matrix.env_arch_key }}: ${{ matrix.arch }}

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.name }}